In [3]:
import numpy as np

In [5]:
my_list=[1,2,3]
np.array(my_list)

array([1, 2, 3])

or

In [8]:
import numpy
my_list=[1,2,3]
numpy.array(my_list)

array([1, 2, 3])

In [10]:
arr1=np.array(11)
arr2=np.array(12)
type(arr1)

numpy.ndarray

In [12]:
arr1+arr2

23

In [14]:
arr1+10

21

In [28]:
arr1+10


21

In [32]:
arr1.ndim
arr1.shape    #dimensions of an array

()

In [34]:
arr1.dtype
                            #32 bit

dtype('int32')

In [38]:
arr4=np.array([1,2,3,4,5,'a'])
arr4

array(['1', '2', '3', '4', '5', 'a'], dtype='<U11')

In [40]:
arr4.shape

(6,)

In [53]:
arr4=np.array([[1,2,4],[5,6,5],[4,6,0]])

In [47]:
arr4.shape

(3, 3)

In [49]:
arr4.size

9

In [61]:
arr5=np.array([[2,4],[4,5]])
arr5.shape

(2, 2)

In [63]:
arr5.size

4

In [65]:
arr5

array([[2, 4],
       [4, 5]])

In [67]:
print(list(range(5,10)))

[5, 6, 7, 8, 9]


In [69]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [77]:
arr5=np.arange(100,10,-3)

In [79]:
arr5


array([100,  97,  94,  91,  88,  85,  82,  79,  76,  73,  70,  67,  64,
        61,  58,  55,  52,  49,  46,  43,  40,  37,  34,  31,  28,  25,
        22,  19,  16,  13])

In [91]:
arr6=np.arange(10,50)
arr6.shape

(40,)

In [101]:
arr6.reshape(20,2)

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35],
       [36, 37],
       [38, 39],
       [40, 41],
       [42, 43],
       [44, 45],
       [46, 47],
       [48, 49]])

In [103]:
arr6.reshape(1,40)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
        26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
        42, 43, 44, 45, 46, 47, 48, 49]])

In [105]:
l=range(1000)
%timeit nums=[i**2 for i in l]

186 μs ± 2.38 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [107]:
nums=np.arange(1000)
%timeit nums**2

3.47 μs ± 66.3 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [109]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [111]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [119]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [121]:
np.diag((3,3))

array([[3, 0],
       [0, 3]])

In [170]:
z=np.diag([3,3])                 #extracting diagonals
np.diag(z)

array([3, 3])

In [133]:
np.diag((45,35))

array([[45,  0],
       [ 0, 35]])

In [137]:
x=np.array(range(1,100))
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [166]:
my_std=np.sqrt(np.sum((x-np.mean(x))**2)/x.size)
print(my_std)                                                #std deviation
print(np.std(x))

28.577380332470412
28.577380332470412


In [168]:
np.std(x)

28.577380332470412

In [190]:

d=np.random.random(3)
d

array([0.56208437, 0.26806396, 0.37644743])

In [200]:
np.random.randn

<function RandomState.randn>

In [182]:
np.random.randint(0,20,3)

array([19,  7,  0])

In [202]:
np.random.randint(0,20,6)

array([18,  6,  2,  2, 18,  5])

In [204]:
a=np.arange(10)

In [206]:
a.dtype

dtype('int32')

In [212]:
a=np.arange(10, dtype=np.float64)

In [214]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [216]:
a.dtype

dtype('float64')

In [218]:
np.array([1+3j]).dtype

dtype('complex128')

In [220]:
a=np.arange(10, dtype=np.int64)

In [222]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int64)

In [224]:
a=np.arange(10,dtype=np.float64)

In [226]:
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [230]:
np.array([True,False,True]).dtype

dtype('bool')

In [232]:
np.array(['hi','hlo'])

array(['hi', 'hlo'], dtype='<U3')

In [234]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [252]:
a[3]=7

In [254]:
a

array([0, 1, 2, 7, 4, 5, 6, 7, 8, 9])

In [240]:
b=a[::2]
b

array([0, 2, 4, 6, 8])

In [256]:
#9,7,5,3,1
b=a[10:0:-2]
b

array([9, 7, 5, 7, 1])

In [261]:
a[1::2][::-1]

array([9, 7, 5, 7, 1])

In [271]:
a[1::2][::-1]

array([9, 7, 5, 7, 1])

In [277]:
a[1::2][::-1][::-1]

array([1, 7, 5, 7, 9])

In [265]:
np.shares_memory(a,b)

True

In [279]:
#concatenation

In [281]:
a=np.zeros((4,4))
b=np.ones((4,4))
print(a)
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [285]:
c=np.vstack((a,b))
c.shape

(8, 4)

In [287]:
d=np.hstack((a,b))
d

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [289]:
d.shape

(4, 8)

In [291]:
np.concatenate([a,b],axis=1)   #hstack

array([[0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.],
       [0., 0., 0., 0., 1., 1., 1., 1.]])

In [295]:
np.concatenate([a,b],axis=0)            #vstack

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [297]:
np.concatenate([a,b],axis=2)

AxisError: axis 2 is out of bounds for array of dimension 2

In [299]:
array1=np.array([1,2,3])
array1.T.shape                 #transpose

(3,)

In [301]:
a=np.arange(4)
b=a.T
np.dot(a,b)                      #dot product

14